### PR TITLE
fix: editing mod tags and authors

### LINKED ISSUE #162: Adding an author to a mod with tags fails and makes the tags list uneditable until the page is refreshed
Steps to reproduce:

1. Have a mod with tags (ex. https://ficsit.app/mod/rTjn8dxD2xha4/), go to the Edit Mod page
2. Try to add an author (ex. `7LTu67kf2o4UvL`)
3. Click save
4. The save does not go through and the Tags field is given focus. No errors in browser console.
5. Click X on one of the tags
6. The tag does not disappear, error produced in browser console Image

Workaround: Remove all of the tags from the mod, save changes, then add the author to the mod, save changes, then add the tags back

### PR DESCRIPTION
**Pull request by knightzac19**
This should resolve #162 and any wonkiness that editing a mod was having due to stale data.

### CODE REVIEW

**Review by budak7273 — DISMISSED** [review]
Tested locally and it fixes #162 for me

File: src/lib/components/utils/TagList.svelte [hunk 1]
```diff
@@ -32,11 +32,11 @@
     target: 'popupAutocomplete',
     placement: 'bottom-start'
   };
-
   let tagList = [];
-  const loadTagList = () => (tagList = tags.map((t: Tag) => t.name));
+  const loadTagList = tags ? () => (tagList = tags.map((t: Tag) => t.name)) : () => {};
```
Comment (mircearoata) [inline src/lib/components/utils/TagList.svelte:36]: `tags` is initialized to `[]`, so the else case of this conditional is never taken

File: src/lib/components/utils/TagList.svelte [hunk 2]
```diff
@@ -32,11 +32,11 @@
...
 
   onMount(loadTagList);
+  afterUpdate(loadTagList);
```
Comment (mircearoata) [inline src/lib/components/utils/TagList.svelte:39]: This could constantly retrigger updates, because it's not a reactive change (`$:`), so setting `tagList` will trigger an update as there are reactive listeners to it (the bindings in the section HTML)

File: src/lib/components/utils/TagList.svelte [hunk 3]
```diff
@@ -55,7 +55,9 @@
   const removeTag = (label: string) => {
     const idx = tags.findIndex((t) => t.name === label);
     tags = [...tags.slice(0, idx), ...tags.slice(idx + 1)];
-
+    if (tags.length == null) {
+      tags = [];
+    }
```
Comment (mircearoata) [inline src/lib/components/utils/TagList.svelte:60]: The variable is set to an array right above this line, so the length can never be null

File: src/routes/mod/[modId]/+page.svelte [hunk 4]
```diff
@@ -101,7 +101,9 @@
       <h1 class="text-4xl font-bold">{$mod.data.mod.name}</h1>
       <div>
         {#if canUserEdit}
-          <button class="variant-ghost-primary btn" on:click={() => goto(base + '/mod/' + modId + '/edit')}>
+          <button
+            class="variant-ghost-primary btn"
+            on:click={() => goto(base + '/mod/' + modId + '/edit', { invalidateAll: true })}>
```
Comment (mircearoata) [inline src/routes/mod/[modId]/+page.svelte:106]: `invalidateAll` is not really a great tool, you almost never need to clear the entire cached data. If you want to forcefully fetch the latest data, urql has `requestPolicy: 'network-only'`

File: src/lib/components/mods/ModForm.svelte [hunk 5]
```diff
@@ -45,14 +46,15 @@
...
-    if (anyData.tags) {
-      tags = anyData.tags;
-      delete anyData.tags;
-    }
+  let tags = $data.tags;
+  const computeTags = () => {
     $data.tagIDs = tags.map((tag) => tag.id);
+  };
+
+  onMount(computeTags);
```
Comment (mircearoata) [inline src/lib/components/mods/ModForm.svelte:54]: `onMount` is rarely needed, it delays actions to after the DOM has been rendered, rather than on component creation (when the script section runs), so it's normally used when something depends on elements existing in the DOM (for example using a variable with `bind:this`)

**Review by mircearoata — COMMENTED** [review]
Most of this is unnecessary, the issue is that the TagsList uses `InputChip` with `name="tags"` which means that on input updates the form data will be updated with the tag chip text, but the tagIDs field is updated from `$data.tags` instead of `tags`, so it reads the `id` field of strings, and ends up being full of `undefined`, failing the validation.

The only thing needed to fix the issue is

```diff
diff --git a/src/lib/components/mods/ModForm.svelte b/src/lib/components/mods/ModForm.svelte
index a62f7e0..8bd9982 100644
--- a/src/lib/components/mods/ModForm.svelte
+++ b/src/lib/components/mods/ModForm.svelte
@@ -45,15 +45,9 @@
     onSubmit: (submitted: ModData) => onSubmit(trimNonSchema(submitted, modSchema))
   });
 
-  let tags = [];
-  $: {
-    const anyData = $data;
-    if (anyData.tags) {
-      tags = anyData.tags;
-      delete anyData.tags;
-    }
-    $data.tagIDs = tags.map((tag) => tag.id);
-  }
+  let tags = $data.tags ?? [];
+
+  $: $data.tagIDs = tags.map((tag) => tag.id);
 
   // The GQL type NewMod does not have a compatibility field.
   // We remove the field from the data so that the GQL request is valid

```

I also left a few pointers about svelte as comments on the code

File: src/lib/components/utils/TagList.svelte (hunk 3 above)
Comment (knightzac19) [reply src/lib/components/utils/TagList.svelte:60]: I was seeing some strange behavior where it was getting set to null, this might not be happening anymore.

File: src/routes/mod/[modId]/+page.svelte (hunk 4 above)
Comment (knightzac19) [reply src/routes/mod/[modId]/+page.svelte:106]: I saw that, but didn't see how to use that, I'll take another look on how to make it use that instead as this fixed a lot stale data issues that made tags mess up.

**Comment by knightzac19** [comment]
> Most of this is unnecessary, the issue is that the TagsList uses `InputChip` with `name="tags"` which means that on input updates the form data will be updated with the tag chip text, but the tagIDs field is updated from `$data.tags` instead of `tags`, so it reads the `id` field of strings, and ends up being full of `undefined`, failing the validation.
> 
> The only thing needed to fix the issue is
> 
> ```diff
> diff --git a/src/lib/components/mods/ModForm.svelte b/src/lib/components/mods/ModForm.svelte
> index a62f7e0..8bd9982 100644
> --- a/src/lib/components/mods/ModForm.svelte
> +++ b/src/lib/components/mods/ModForm.svelte
> @@ -45,15 +45,9 @@
>      onSubmit: (submitted: ModData) => onSubmit(trimNonSchema(submitted, modSchema))
>    });
>  
> -  let tags = [];
> -  $: {
> -    const anyData = $data;
> -    if (anyData.tags) {
> -      tags = anyData.tags;
> -      delete anyData.tags;
> -    }
> -    $data.tagIDs = tags.map((tag) => tag.id);
> -  }
> +  let tags = $data.tags ?? [];
> +
> +  $: $data.tagIDs = tags.map((tag) => tag.id);
>  
>    // The GQL type NewMod does not have a compatibility field.
>    // We remove the field from the data so that the GQL request is valid
> ```
> 
> I also left a few pointers about svelte as comments on the code

Alright, I cleaned up most of the code, I was running into a lot of strange non-updating issues and undefined issues which led me down a rabbit hole. So getting rid of a lot of the extra code still let things work properly.

**Comment by mircearoata** [comment]
I guess you're referring to the redirect back to the mod page after editing twice being blank. That one is really odd, because the API returns `null` for the tags on the `UpdateMod` mutation, but not for the authors, which are also a relation, and I don't see how this could even be happening, but refetching the data does work around this issue, and it shouldn't cause that many extra queries (unless someone is constantly navigating between the mods list and a mod page)

**Review by mircearoata — APPROVED** [review]
